title: Course Syllabus
description: Introduction to Computer Science Syllabus
author: Dr. Smith
email: smith@university.edu

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima theme settings
minima:
  date_format: "%b %-d, %Y"

# Social links (optional)
# twitter_username: 
# github_username:  
# linkedin_username: 

# If you want to link only specific pages in your header, add the path to the
# pages here, and remove the pages field above
header_pages:
  - syllabus.md

# Show excerpts on the home page
show_excerpts: false
