title: Introduction to Computer Science
description: Course Syllabus - Fall 2025
author: Dr. Smith
email: smith@university.edu

# Build settings
remote_theme: pages-themes/slate@v0.2.0
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Jekyll settings
lsi: false
safe: true
incremental: false
  - jekyll-seo-tag

# Theme-specific settings
show_downloads: false
google_analytics:
github:
  is_project_page: false
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima theme settings
minima:
  date_format: "%b %-d, %Y"

# Social links (optional)
# twitter_username: 
# github_username:  
# linkedin_username: 

# If you want to link only specific pages in your header, add the path to the
# pages here, and remove the pages field above
header_pages:
  - syllabus.md

# Show excerpts on the home page
show_excerpts: false
